name: Build PDF of the Book
# This Workflow was adapted from the official docs:
# https://github.com/executablebooks/jupyter-book

on:
  push:
    branches:
      - main

  workflow_dispatch:
  repository_dispatch:

jobs:
  pdf_from_latex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pipx
          git clone https://github.com/executablebooks/jupyter-book.git
          pipx install -e ./jupyter-book[sphinx,pdflatex]

      - name: Install latex dependencies
        run: >
          sudo apt-get -qq update &&
          sudo apt-get install -y
          texlive-latex-recommended
          texlive-latex-extra
          texlive-fonts-extra
          fonts-freefont-otf
          texlive-xetex
          latexmk
          xindy

      - name: Build PDF from LaTeX
        run: jb build . --builder pdflatex

      - uses: actions/upload-artifact@v4
        with:
          name: Book PDF
          path: _build/latex/book.pdf
